name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=20.3.3
  - hydra-core=1.3.2
  - mlflow=2.0.1
  - pip:
      - wandb==0.10.21
