name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests=2.31.0
  - pip=20.3.3
  - mlflow=2.0.1
  - hydra-core=1.3.2
  - cookiecutter=1.7.2
  - pip:
      - wandb==0.10.31