channels:
- conda-forge
dependencies:
- python=3.8.17
- pip<=20.3.3
- pip:
  - mlflow==2.4
  - cloudpickle==2.2.1
  - numpy==1.24.4
  - pandas==2.0.3
  - psutil==5.9.5
  - scikit-learn==1.3.0
  - scipy==1.10.1
name: mlflow-env
